# Generated by Django 4.2.5 on 2023-09-16 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(default=None, max_length=12, null=True)),
                ('Kind', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=20)),
                ('num', models.IntegerField()),
                ('password', models.CharField(max_length=10)),
                ('score', models.IntegerField(default=0)),
            ],
        ),
    ]
